[package]
name = "roseraie-planning"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "roseraie-planning"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
itertools = "0.13.0"
time = "0.3.37"
