name: Code Coverage

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable

      - name: Run unit tests with code coverage
        run: RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-unit-%p-%m.profraw' cargo test --lib --verbose

      - name: Install grcov tool and dependency (llvm-tools)
        run: |
          cargo install grcov
          rustup component add llvm-tools-preview

      # Report using zgosalvez/github-actions-report-lcov
      - name: Build code coverage LCOV report
        run: |
          mkdir -p target/coverage
          grcov . --keep-only 'src/*' --binary-path ./target/debug/deps/ --source-dir . --output-types lcov --branch --ignore-not-existing --output-path target/coverage/lcov.tests.info
      - name: Install lcov
        run: sudo apt-get install lcov
      - name: Report code coverage in Pull Request
        uses: zgosalvez/github-actions-report-lcov@v4.1.21
        with:
          coverage-files: target/coverage/lcov.*.info
          artifact-name: code-coverage-report
          minimum-coverage: 30
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
